export {
  ACCENT_COLOR,
  MUTED_COLOR,
  TEXT_COLOR,
  ctaButton,
  emailEyebrow,
  emailGreeting,
  emailHeading,
  emailLayout,
  emailMuted,
  emailParagraph,
  infoTable,
  orderReference,
  otpBlock,
  totalRow,
  type LayoutOptions,
} from '@/services/email/templates/layout';
