/**
 * Curated icon barrel. Import icons from here instead of `lucide-react`
 * directly so the icon set used across the app stays discoverable and
 * easy to swap out in one place.
 */
export type { LucideIcon, LucideProps } from 'lucide-react';

export {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Bold,
  Calendar as CalendarIcon,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Compass,
  Eye,
  EyeOff,
  Facebook,
  File,
  Filter,
  Hammer,
  Heart,
  ImageOff,
  ImagePlus,
  Inbox,
  Instagram,
  Italic,
  List,
  ListOrdered,
  Loader2,
  Lock,
  Mail,
  Menu,
  MinusCircle,
  MoreHorizontal,
  Package,
  Pause,
  Phone,
  Play,
  Plus,
  PlusCircle,
  RotateCw,
  Search,
  ServerCrash,
  Settings,
  ShoppingBag,
  SlidersHorizontal,
  Star,
  Trash2,
  Truck,
  Twitter,
  Underline,
  Upload,
  User,
  Volume2,
  VolumeX,
  WifiOff,
  X,
} from 'lucide-react';
