import { PERMISSIONS, type PermissionKey } from '@/constants/permissions';
import { ROLES, type RoleKey } from '@/constants/roles';

const P = PERMISSIONS;

const ALL_PERMS = Object.values(PERMISSIONS) as PermissionKey[];

const CUSTOMER_PERMS: PermissionKey[] = [
  P.ACCOUNT_READ,
  P.ACCOUNT_UPDATE,
  P.ORDERS_READ_OWN,
  P.ORDERS_CANCEL_OWN,
  P.WISHLIST_MANAGE,
  P.REVIEWS_CREATE,
  P.QA_CREATE,
  P.ADDRESSES_MANAGE,
  P.CART_MANAGE,
  P.CHECKOUT_MANAGE,
  P.PAYMENTS_CREATE,
  P.PAYMENTS_VIEW_OWN,
  P.ORDERS_RETURN_OWN,
];

const GUEST_PERMS: PermissionKey[] = [];

export const ROLE_SEED: Array<{
  key: RoleKey;
  name: string;
  description: string;
  permissions: PermissionKey[];
}> = [
  {
    key: ROLES.SUPER_ADMIN,
    name: 'Super Admin',
    description: 'Full platform control',
    permissions: ALL_PERMS,
  },
  {
    key: ROLES.ADMIN,
    name: 'Admin',
    description: 'Day-to-day operations',
    permissions: ALL_PERMS.filter((p) => p !== P.ROLES_MANAGE),
  },
  {
    key: ROLES.MANAGER,
    name: 'Manager',
    description: 'Catalog, orders, content oversight',
    permissions: [
      P.CUSTOMERS_READ,
      P.CUSTOMERS_VIEW,
      P.CUSTOMERS_UPDATE,
      P.CUSTOMERS_DELETE,
      P.CUSTOMERS_NOTES,
      P.CUSTOMERS_TAGS,
      P.CART_VIEW,
      P.CHECKOUT_VIEW,
      P.PAYMENTS_VIEW,
      P.PRODUCTS_READ,
      P.PRODUCTS_VIEW,
      P.PRODUCTS_CREATE,
      P.PRODUCTS_UPDATE,
      P.PRODUCTS_DELETE,
      P.PRODUCTS_PUBLISH,
      P.PRODUCTS_EXPORT,
      P.PRODUCTS_IMPORT,
      P.ATTRIBUTES_VIEW,
      P.ATTRIBUTES_MANAGE,
      P.CATEGORIES_VIEW,
      P.CATEGORIES_CREATE,
      P.CATEGORIES_UPDATE,
      P.CATEGORIES_DELETE,
      P.CATEGORIES_MANAGE,
      P.CATEGORIES_READ,
      P.BRANDS_VIEW,
      P.BRANDS_CREATE,
      P.BRANDS_UPDATE,
      P.BRANDS_DELETE,
      P.BRANDS_MANAGE,
      P.BRANDS_READ,
      P.COLLECTIONS_VIEW,
      P.COLLECTIONS_CREATE,
      P.COLLECTIONS_UPDATE,
      P.COLLECTIONS_DELETE,
      P.COLLECTIONS_MANAGE,
      P.COLLECTIONS_READ,
      P.COLORS_VIEW,
      P.COLORS_MANAGE,
      P.SIZES_VIEW,
      P.SIZES_MANAGE,
      P.MATERIALS_VIEW,
      P.MATERIALS_MANAGE,
      P.TAGS_VIEW,
      P.TAGS_MANAGE,
      P.OCCASIONS_VIEW,
      P.OCCASIONS_MANAGE,
      P.SEASONS_VIEW,
      P.SEASONS_MANAGE,
      P.INVENTORY_READ,
      P.INVENTORY_VIEW,
      P.INVENTORY_CREATE,
      P.INVENTORY_UPDATE,
      P.INVENTORY_ADJUST,
      P.INVENTORY_TRANSFER,
      P.INVENTORY_RESERVE,
      P.INVENTORY_EXPORT,
      P.WAREHOUSE_MANAGE,
      P.WAREHOUSES_MANAGE,
      P.WAREHOUSES_READ,
      P.SUPPLIER_MANAGE,
      P.PURCHASE_ORDER_MANAGE,
      P.ORDERS_READ,
      P.ORDERS_UPDATE,
      P.ORDERS_CANCEL,
      P.ORDERS_VIEW,
      P.ORDERS_NOTES,
      P.ORDERS_INVOICE,
      P.ORDERS_RETURN_MANAGE,
      P.SHIPPING_MANAGE,
      P.CMS_VIEW,
      P.CMS_MANAGE,
      P.BANNERS_VIEW,
      P.BANNERS_MANAGE,
      P.PAGES_VIEW,
      P.PAGES_MANAGE,
      P.BLOGS_VIEW,
      P.BLOGS_MANAGE,
      P.BLOGS_PUBLISH,
      P.FAQS_VIEW,
      P.FAQS_MANAGE,
      P.MARKETING_VIEW,
      P.MARKETING_MANAGE,
      P.SETTINGS_VIEW,
      P.SETTINGS_READ,
      P.REVIEWS_MODERATE,
      P.QA_MANAGE,
      P.ANALYTICS_VIEW,
      P.REPORTS_VIEW,
    ],
  },
  {
    key: ROLES.INVENTORY_MANAGER,
    name: 'Inventory Manager',
    description: 'Warehouses and stock',
    permissions: [
      P.PRODUCTS_READ,
      P.PRODUCTS_VIEW,
      P.WAREHOUSES_READ,
      P.WAREHOUSES_MANAGE,
      P.WAREHOUSE_MANAGE,
      P.INVENTORY_READ,
      P.INVENTORY_VIEW,
      P.INVENTORY_CREATE,
      P.INVENTORY_UPDATE,
      P.INVENTORY_ADJUST,
      P.INVENTORY_TRANSFER,
      P.INVENTORY_RESERVE,
      P.INVENTORY_EXPORT,
      P.SUPPLIER_MANAGE,
      P.PURCHASE_ORDER_MANAGE,
      P.ORDERS_READ,
      P.ORDERS_VIEW,
      P.ANALYTICS_VIEW,
    ],
  },
  {
    key: ROLES.MARKETING_MANAGER,
    name: 'Marketing Manager',
    description: 'Campaigns, banners, coupons, newsletter',
    permissions: [
      P.CUSTOMERS_READ,
      P.CUSTOMERS_VIEW,
      P.CUSTOMERS_TAGS,
      P.PRODUCTS_READ,
      P.PRODUCTS_VIEW,
      P.CATEGORIES_VIEW,
      P.CATEGORIES_MANAGE,
      P.CATEGORIES_READ,
      P.BRANDS_VIEW,
      P.BRANDS_MANAGE,
      P.BRANDS_READ,
      P.COLLECTIONS_VIEW,
      P.COLLECTIONS_MANAGE,
      P.COLLECTIONS_READ,
      P.COLORS_MANAGE,
      P.SIZES_MANAGE,
      P.MATERIALS_MANAGE,
      P.TAGS_MANAGE,
      P.OCCASIONS_MANAGE,
      P.SEASONS_MANAGE,
      P.COUPONS_READ,
      P.COUPONS_MANAGE,
      P.CMS_VIEW,
      P.CMS_MANAGE,
      P.BANNERS_VIEW,
      P.BANNERS_MANAGE,
      P.PAGES_VIEW,
      P.PAGES_MANAGE,
      P.MARKETING_VIEW,
      P.MARKETING_MANAGE,
      P.BLOGS_VIEW,
      P.BLOGS_MANAGE,
      P.BLOGS_PUBLISH,
      P.FAQS_VIEW,
      P.FAQS_MANAGE,
      P.TEMPLATES_VIEW,
      P.TEMPLATES_MANAGE,
      P.ANALYTICS_VIEW,
      P.REPORTS_VIEW,
    ],
  },
  {
    key: ROLES.CUSTOMER_SUPPORT,
    name: 'Customer Support',
    description: 'Customers, limited orders, inbox',
    permissions: [
      P.CUSTOMERS_READ,
      P.CUSTOMERS_VIEW,
      P.CUSTOMERS_UPDATE,
      P.CUSTOMERS_NOTES,
      P.CUSTOMERS_TAGS,
      P.CART_VIEW,
      P.CHECKOUT_VIEW,
      P.PAYMENTS_VIEW,
      P.SUPPORT_INBOX,
      P.ORDERS_READ,
      P.ORDERS_VIEW,
      P.ORDERS_CANCEL,
      P.ORDERS_NOTES,
      P.ORDERS_RETURN_MANAGE,
      P.REVIEWS_MODERATE,
      P.QA_MANAGE,
    ],
  },
  {
    key: ROLES.FINANCE,
    name: 'Finance',
    description: 'Payments, refunds, gift cards, reports',
    permissions: [
      P.CUSTOMERS_READ,
      P.CUSTOMERS_VIEW,
      P.ORDERS_READ,
      P.ORDERS_VIEW,
      P.ORDERS_REFUND,
      P.ORDERS_INVOICE,
      P.PAYMENTS_READ,
      P.PAYMENTS_RECONCILE,
      P.PAYMENTS_VIEW,
      P.PAYMENTS_REFUND,
      P.PAYMENTS_EXPORT,
      P.GIFTCARDS_READ,
      P.GIFTCARDS_MANAGE,
      P.REPORTS_VIEW,
      P.REPORTS_EXPORT,
      P.ANALYTICS_VIEW,
      P.AUDIT_READ,
    ],
  },
  {
    key: ROLES.WAREHOUSE_STAFF,
    name: 'Warehouse Staff',
    description: 'Pack/ship and stock view/adjust',
    permissions: [
      P.INVENTORY_READ,
      P.INVENTORY_VIEW,
      P.INVENTORY_ADJUST,
      P.INVENTORY_TRANSFER,
      P.INVENTORY_RESERVE,
      P.WAREHOUSES_READ,
      P.ORDERS_READ,
      P.ORDERS_VIEW,
      P.ORDERS_UPDATE,
      P.SHIPPING_MANAGE,
    ],
  },
  {
    key: ROLES.CUSTOMER,
    name: 'Customer',
    description: 'Storefront customer',
    permissions: CUSTOMER_PERMS,
  },
  {
    key: ROLES.GUEST,
    name: 'Guest',
    description: 'Anonymous visitor capabilities (enforced via public routes)',
    permissions: GUEST_PERMS,
  },
];
