export const ADMIN_ROUTES = {
  root: '/admin',
  dashboard: '/admin/dashboard',
  products: '/admin/products',
  productNew: '/admin/products/new',
  productDetail: '/admin/products/$productId',
  categories: '/admin/categories',
  collections: '/admin/collections',
  brands: '/admin/brands',
  inventory: '/admin/inventory',
  orders: '/admin/orders',
  orderDetail: '/admin/orders/$orderId',
  customers: '/admin/customers',
  customerDetail: '/admin/customers/$customerId',
  cms: '/admin/cms',
  cmsPages: '/admin/cms/pages',
  cmsBanners: '/admin/cms/banners',
  cmsHome: '/admin/cms/home',
  marketing: '/admin/marketing',
  finance: '/admin/finance',
  reports: '/admin/reports',
  users: '/admin/users',
  roles: '/admin/roles',
  settings: '/admin/settings',
  audit: '/admin/audit',
  login: '/login',
  forbidden: '/admin/forbidden',
} as const;
